# src/simulation_utils.py
"""
Utility functions for running ElmerGrid, ElmerSolver, and parsing simulation results.
"""
import os
import subprocess
from pyelmer.post import scan_logfile

def run_elmer_grid(mesh_dir, mesh_filepath, meshout_dir, in_format="8", out_format="2", elmergrid=None):
    """
    Runs ElmerGrid to convert a mesh file to Elmer's format.

    Args:
        mesh_dir (str): The directory containing the mesh file.
        mesh_filepath (str): The full path to the input mesh file (e.g., .unv).
        meshout_dir (str): The directory where the output mesh will be saved.
        in_format (str): The input mesh format code for ElmerGrid. '8' for UNV.
        out_format (str): The output mesh format code. '2' for Elmer's mesh format.
        elmergrid (str, optional): Path to the ElmerGrid executable. Defaults to finding it.
    """
    if elmergrid is None:
        if os.path.exists("C:/Program Files/Elmer 9.0-Release/bin/ElmerGrid.exe"):
            elmergrid = "C:/Program Files/Elmer 9.0-Release/bin/ElmerGrid.exe"
        else:
            elmergrid = "ElmerGrid"

    args = [elmergrid, in_format, out_format, mesh_filepath, "-autoclean", "-out", os.path.abspath(meshout_dir)]
    os.makedirs(os.path.dirname(meshout_dir), exist_ok=True)

    log_path = os.path.join(mesh_dir, "elmergrid.log")
    with open(log_path, "w") as f:
        subprocess.run(args, cwd=mesh_dir, stdout=f, stderr=subprocess.STDOUT, input=b"y\n", check=True)

def run_elmer_solver(sim_dir):
    """
    Executes the ElmerSolver in a given simulation directory.

    Args:
        sim_dir (str): The path to the simulation directory containing the SIF file.
    """
    scalar_filepath = os.path.join(sim_dir, "result", "scalar", "integrais_bobina.dat")
    if os.path.exists(scalar_filepath):
        os.remove(scalar_filepath)

    # Executa o solver passando o arquivo SIF diretamente, assumindo o nome padrão 'case.sif' do pyelmer
    solver_process = subprocess.run(["ElmerSolver", "case.sif"], cwd=sim_dir, capture_output=True, text=True)

    with open(os.path.join(sim_dir, "elmersolver.log"), "w") as log_file:
        log_file.write(solver_process.stdout)
        if solver_process.stderr:
            log_file.write("\n--- STDERR ---\n" + solver_process.stderr)

    print("  -> Checking solver log...")
    err, warn, _ = scan_logfile(sim_dir)
    if err:
        print(f"     !! Elmer errors found: {err}")
    if warn:
        print(f"     -- Elmer warnings found: {warn}")

def parse_scalar_results(scalar_filepath, N_turns, depth, current):
    """
    Parses the scalar results file generated by the SaveScalars solver.

    Args:
        scalar_filepath (str): Path to the scalar data file.
        N_turns (int): Number of turns in the coil.
        depth (float): Depth of the 2D model.
        current (float): The current for this simulation step.

    Returns:
        tuple: A tuple containing (magnetic_flux, magnetic_energy, inductance).
    """
    with open(scalar_filepath, "r") as f:
        last_line = f.readlines()[-1]
        results = [float(val) for val in last_line.split()]
        
        # The columns in 'integrais_bobina.dat' are defined by the SaveScalars solver in the SIF.
        # Here, we assume:
        # results[0]: Integral of "Potential" over the body area (Integral Area)
        # results[1]: Integral of "Potential" over the body (Integral Potencial)
        # results[3]: Integral of "Magnetic Energy"
        
        # Calculate magnetic flux (Phi = V_avg * N * depth)
        magnetic_flux = (results[1] / results[0] * N_turns) * depth
        
        # Calculate total magnetic energy (W = integral(w) * depth)
        magnetic_energy = results[3] * depth
        
        # Calculate inductance (L = Phi / I)
        if current == 0.0:
            inductance = 0.0
        else:
            inductance = magnetic_flux / current
            
        return magnetic_flux, magnetic_energy, inductance
